
---
apiVersion:  v1
kind: Pod
metadata:
  name:  hellowworldapppod        #Name is difinite
  labels:
    app: helowworldappconnector                    #key abc app and name not difinite
  namespace: valaxyapplication 
spec:
  containers:
  - name:  hellowworldappcontainer         #name of a container
    image:  agunuworld/hellowworldapp:17            #which images u want to create a container
    ports:
    - containerPort: 8090
    
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: helloworldappservice                             #service name varies it can be any name
  namespace: valaxyapplication 
spec:
  type: NodePort                                             #type of service and we have two types of services NodePortip and Notepod
  selector:
     app: hellowwworldappconnector                                     #this selector helps to identify the label created in the pod
  ports:
  - port: 80                                                  #default
    targetPort: 8090    #target application of the pod ap
    nodePort: 30001
